name: app_template
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.9
  flutter: ">=3.41.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  firebase_messaging: ^16.0.4
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  flutter_secure_storage: ^10.0.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  health: ^13.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  analyzer: ^8.4.1
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_gen_runner: ^5.12.0
  json_serializable: ^6.11.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/generated/
